INSERT INTO answers_2 (ANSWER_KEY, ANSWER)
VALUES (1, '매우 그렇다');

INSERT INTO answers_2 (ANSWER_KEY, ANSWER)
VALUES (2, '그렇다');

INSERT INTO answers_2 (ANSWER_KEY, ANSWER)
VALUES (3, '보통이다');

INSERT INTO answers_2 (ANSWER_KEY, ANSWER)
VALUES (4, '그렇지 않다');

INSERT INTO answers_2 (ANSWER_KEY, ANSWER)
VALUES (5, '매우 그렇지 않다');