INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (1, "감자바");

INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (2, "나운영");

INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (3, "김기영");

INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (4, "조성혜");

INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (5, "도날드");

INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (6, "가면왕");

INSERT INTO responses_2 (RESPONSE_NUMBER, NAME)
VALUES (7, "미역국");