
CREATE TABLE ANS
(
  ANSWER_KEY int          NOT NULL,
  ANSWER     varchar(200) NULL    ,
  PRIMARY KEY (ANSWER_KEY)
);

CREATE TABLE QUEST
(
  QUESTION_KEY int          NOT NULL,
  QUESTION     varchar(200) NULL    ,
  PRIMARY KEY (QUESTION_KEY)
);

CREATE TABLE QUEST_AND_ANS
(
  ANSWER_KEY   int NOT NULL,
  QUESTION_KEY int NOT NULL,
  TOTAL_KEY    int NOT NULL
);

CREATE TABLE RESPONSES
(
  RESPONSE_NUMBER int          NOT NULL,
  NAME            varchar(200) NULL    ,
  PRIMARY KEY (RESPONSE_NUMBER)
);

CREATE TABLE TOTAL
(
  RESPONSE_NUMBER int NOT NULL,
  TOTAL_KEY       int NOT NULL,
  PRIMARY KEY (TOTAL_KEY)
);

ALTER TABLE TOTAL
  ADD CONSTRAINT FK_RESPONSES_TO_TOTAL
    FOREIGN KEY (RESPONSE_NUMBER)
    REFERENCES RESPONSES (RESPONSE_NUMBER);

ALTER TABLE QUEST_AND_ANS
  ADD CONSTRAINT FK_ANS_TO_QUEST_AND_ANS
    FOREIGN KEY (ANSWER_KEY)
    REFERENCES ANS (ANSWER_KEY);

ALTER TABLE QUEST_AND_ANS
  ADD CONSTRAINT FK_QUEST_TO_QUEST_AND_ANS
    FOREIGN KEY (QUESTION_KEY)
    REFERENCES QUEST (QUESTION_KEY);

ALTER TABLE QUEST_AND_ANS
  ADD CONSTRAINT FK_TOTAL_TO_QUEST_AND_ANS
    FOREIGN KEY (TOTAL_KEY)
    REFERENCES TOTAL (TOTAL_KEY);
