
CREATE TABLE ANSWERS_2
(
  ANSWER_KEY int          NOT NULL,
  ANSWER     varchar(200) NULL    ,
  PRIMARY KEY (ANSWER_KEY)
);

CREATE TABLE QUESTIONS_2
(
  QUESTION_KEY int          NOT NULL,
  QUESTION     varchar(200) NULL    ,
  PRIMARY KEY (QUESTION_KEY)
);

CREATE TABLE QUESTIONS_AND_ANSWERS_2
(
  ANSWER_KEY   int NOT NULL,
  QUESTION_KEY int NOT NULL,
  TOTAL_KEY    int NOT NULL,
  PRIMARY KEY (TOTAL_KEY)
);

CREATE TABLE RESPONSES_2
(
  RESPONSE_NUMBER int          NOT NULL,
  NAME            varchar(200) NULL    ,
  PRIMARY KEY (RESPONSE_NUMBER)
);

CREATE TABLE TOTAL_QUESTIONS_2
(
  RESPONSE_NUMBER int NOT NULL,
  TOTAL_KEY       int NOT NULL
);

ALTER TABLE TOTAL_QUESTIONS_2
  ADD CONSTRAINT FK_RESPONSES_2_TO_TOTAL_QUESTIONS_2
    FOREIGN KEY (RESPONSE_NUMBER)
    REFERENCES RESPONSES_2 (RESPONSE_NUMBER);

ALTER TABLE QUESTIONS_AND_ANSWERS_2
  ADD CONSTRAINT FK_ANSWERS_2_TO_QUESTIONS_AND_ANSWERS_2
    FOREIGN KEY (ANSWER_KEY)
    REFERENCES ANSWERS_2 (ANSWER_KEY);

ALTER TABLE QUESTIONS_AND_ANSWERS_2
  ADD CONSTRAINT FK_QUESTIONS_2_TO_QUESTIONS_AND_ANSWERS_2
    FOREIGN KEY (QUESTION_KEY)
    REFERENCES QUESTIONS_2 (QUESTION_KEY);

ALTER TABLE TOTAL_QUESTIONS_2
  ADD CONSTRAINT FK_QUESTIONS_AND_ANSWERS_2_TO_TOTAL_QUESTIONS_2
    FOREIGN KEY (TOTAL_KEY)
    REFERENCES QUESTIONS_AND_ANSWERS_2 (TOTAL_KEY);
