INSERT INTO total_questions_2 (RESPONSE_NUMBER, TOTAL_KEY)
VALUES (1, 1);

INSERT INTO total_questions_2 (RESPONSE_NUMBER, TOTAL_KEY)
VALUES (1, 2);

INSERT INTO total_questions_2 (RESPONSE_NUMBER, TOTAL_KEY)
VALUES (1, 3);

INSERT INTO total_questions_2 (RESPONSE_NUMBER, TOTAL_KEY)
VALUES (1, 4);